version: "3.7"
services:
  api:
    env_file:
      - ./.env
    build: .
    entrypoint: ./run.sh
    volumes:
      - .:/usr/app
    ports:
      - "54000:54000"
    extra_hosts:
      - "host.docker.internal:10.0.2.15"
