version: "3.7"
services:
  redis:
    image: redis
    container_name: ${REDIS_NAME}
    expose:
      - ${REDIS_PORT}
  api:
    links:
      - redis
    env_file:
      - ./env/.env
    build: .
    volumes:
      - .:/usr/app
    ports:
      - "${SERVER_PORT}:${INTERNAL_SERVER_PORT}"
    extra_hosts:
      - "${HOST_NAME}:${HOST_IP}"
