version: "3.7"
services:
  redis:
    image: redis:alpine
    volumes:
      - ../data/redis/:/data
    entrypoint: redis-server --appendonly yes
  api:
    image: toec_server:latest
    env_file:
      - ./env/.env
    volumes:
      - .:/usr/app
    ports:
      - "${SERVER_PORT}:${INTERNAL_SERVER_PORT}"
    extra_hosts:
      - "${HOST_NAME}:${HOST_IP}"
